#
# Docker compose file for development
#

version: "3"

services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/nginx_host.conf:/etc/nginx/conf.d/default.conf:ro
      - ../:/code
    ports:
      - 8081:80
    depends_on:
      - php-fpm

  php-fpm:
    build: ./php-fpm
    environment:
      PHP_IDE_CONFIG: "serverName=govwiki_filelib"
    volumes:
      - ../:/code

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: govwiki_filelib
    volumes:
      - ./db:/var/lib/mysql
